spring:
  datasource:
    flyway:
      url: jdbc:mysql://localhost:3306/noname-school
      user: admin
      password: qwer1595@!
    url: jdbc:mysql://localhost:3306/noname-school
    username: admin
    password: qwer1595@!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      max-lifetime: 600000
      idle-timeout: 59000
      dns-cache-ttl: 30
  flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 1
    locations: classpath:migration
    sqlMigrationSuffixes: sql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: false
logging:
#  level:
#    com.zaxxer.hikari.HikariConfig: debug
#    com.zaxxer.hikari: trace
#    org:
#      springframework:
#        transaction:
#          interceptor: trace
springdoc:
  swagger-ui:
    enabled: false